#!/bin/sh
# AutoUPnP LD_PRELOAD setup helper
# (c) 2010 Michał Górny
# Released under the terms of the 3-clause BSD license

print_help() {
	cat <<_EOF_
Usage:

autoupnp
	to execute subshell with AutoUPnP LD_PRELOAD enabled.
autoupnp <command> [...]
	to execute the command with AutoUPnP LD_PRELOAD enabled.
eval "\$(autoupnp on)"
	to export AutoUPnP LD_PRELOAD to the currently running shell.
eval "\$(autoupnp off)"
	to remove AutoUPnP from LD_PRELOAD in the currently running shell.
autoupnp install
	to add the '. autoupnp on' call to your ~/.bash_profile, ~/.profile...
autoupnp uninstall
	to remove the '. autoupnp on' from your ~/.bash_profile, ~/.profile...
_EOF_
}

enable_preload() {
	set -- ${LD_PRELOAD}
	while [ ${#} -gt 0 ]; do
		[ ${1} = 'autoupnp.so' ] && return
		shift
	done

	echo 'export LD_PRELOAD="${LD_PRELOAD+${LD_PRELOAD} }autoupnp.so"'
}

disable_preload() {
	set -- ${LD_PRELOAD}

	unset LD_PRELOAD
	while [ ${#} -gt 0 ]; do
		[ ${1} != 'autoupnp.so' ] \
				&& LD_PRELOAD=${LD_PRELOAD+${LD_PRELOAD} }${1}
		shift
	done

	if [ -n "${LD_PRELOAD}" ]; then
		printf 'export LD_PRELOAD="%s"\n' "$(echo "${LD_PRELOAD}" | sed -e 's:":\\":')"
	else
		echo 'unset LD_PRELOAD'
	fi
}

install_preload() {
	if [ ${#} -gt 0 ]; then
		while [ ${#} -gt 0 ]; do
			echo "XXX: install in ${1}" >&2
			shift
		done
	else
		set -- ~/.bash_profile bash ~/.zprofile zsh

		while [ ${#} -gt 0 ]; do
			if [ -f "${1}" ]; then
				if [ ! -f ~/.profile ] || ! grep '\(\.\|source\) ~/.profile' "${1}" >/dev/null; then
					install_preload "${1}"
				fi
			elif [ -x /bin/${2} ]; then
				echo "NOTICE: if you'd like to have AutoUPnP enabled for ${2} shell, please:" >&2
				echo "$ touch ${1}" >&2
			fi

			shift
			shift
		done

		if [ -f ~/.profile ]; then
			install_preload ~/.profile
		elif ! cmp -s /bin/sh /bin/bash && ! cmp -s /bin/sh /bin/zsh; then
			echo 'WARNING: /bin/sh seems to not match /bin/{bash,zsh} but no ~/.profile' >&2
			echo "exists. If you'd like to enable AutoUPnP for non-bash POSIX shells like" >&2
			echo 'dash, please first: $ touch ~/.profile' >&2
			if [ -f ~/.bash_profile -o -f ~/.zprofile ]; then
				echo >&2
				echo 'You might also consider moving your ~/.bash_profile and/or ~/.zprofile' >&2
				echo 'declarations to ~/.profile and sourcing the latter file within the former.' >&2
			fi
		fi
	fi
}

uninstall_preload() {
	echo 'XXX: not yet implemented' >&2
}

if [ ${#} -gt 0 ]; then
	case "${1}" in
		-h|-?|--help)
			print_help
			;;
		on)
			enable_preload
			;;
		off)
			disable_preload
			;;
		install)
			shift
			install_preload "${@}"
			;;
		uninstall)
			uninstall_preload
			;;
		*)
			enable_preload
			exec "${@}"
	esac
else
	echo 'Starting AutoUPnP-enabled shell.' >&2
	enable_preload
	exec "${SHELL:-/bin/sh}"
fi
